/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART0 receive data source select: UART0_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART0 transmit data source select: UART0_TX pin */

/*! @name PORTA2 (number 28), J1[4]/D1/UART0_TX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                                /* @} */

/*! @name PORTA1 (number 27), J1[2]/D0/UART0_RX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                                /* @} */

/*! @name PORTC1 (number 56), J10[12]/U6[31]/A5
  @{ */
#define BOARD_INITPINS_LCD_RS_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_LCD_RS_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_RS_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_RS_PIN 1U     /*!<@brief PORTC pin index: 1 */
                                         /* @} */

/*! @name PORTC2 (number 57), J10[10]/A4
  @{ */
#define BOARD_INITPINS_LCD_RW_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_LCD_RW_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_RW_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_RW_PIN 2U     /*!<@brief PORTC pin index: 2 */
                                         /* @} */

/*! @name PORTE30 (number 22), J10[11]
  @{ */
#define BOARD_INITPINS_LCD_E_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_LCD_E_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_LCD_E_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LCD_E_PIN 30U    /*!<@brief PORTE pin index: 30 */
                                        /* @} */

/*! @name PORTB0 (number 43), J10[2]/A0
  @{ */
#define BOARD_INITPINS_LCD_D0_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_LCD_D0_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LCD_D0_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LCD_D0_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                         /* @} */

/*! @name PORTB1 (number 44), J10[4]/A1
  @{ */
#define BOARD_INITPINS_LCD_D1_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_LCD_D1_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LCD_D1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LCD_D1_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                         /* @} */

/*! @name PORTB2 (number 45), J10[6]/A2
  @{ */
#define BOARD_INITPINS_LCD_D2_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_LCD_D2_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LCD_D2_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LCD_D2_PIN 2U     /*!<@brief PORTB pin index: 2 */
                                         /* @} */

/*! @name PORTB3 (number 46), J10[8]/A3
  @{ */
#define BOARD_INITPINS_LCD_D3_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_LCD_D3_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LCD_D3_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LCD_D3_PIN 3U     /*!<@brief PORTB pin index: 3 */
                                         /* @} */

/*! @name PORTE20 (number 13), J10[1]
  @{ */
#define BOARD_INITPINS_LCD_D4_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_LCD_D4_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_LCD_D4_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LCD_D4_PIN 20U    /*!<@brief PORTE pin index: 20 */
                                         /* @} */

/*! @name PORTE21 (number 14), J10[3]
  @{ */
#define BOARD_INITPINS_LCD_D5_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_LCD_D5_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_LCD_D5_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LCD_D5_PIN 21U    /*!<@brief PORTE pin index: 21 */
                                         /* @} */

/*! @name PORTE22 (number 15), J10[5]
  @{ */
#define BOARD_INITPINS_LCD_D6_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_LCD_D6_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_LCD_D6_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LCD_D6_PIN 22U    /*!<@brief PORTE pin index: 22 */
                                         /* @} */

/*! @name PORTE23 (number 16), J10[7]
  @{ */
#define BOARD_INITPINS_LCD_D7_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_LCD_D7_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_LCD_D7_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LCD_D7_PIN 23U    /*!<@brief PORTE pin index: 23 */
                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
